// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCgbJxEfn0AUJvJB1mHY_FM6mjQDaBMY',
    appId: '1:271186785582:web:155e87fa341cd7b66536bf',
    messagingSenderId: '271186785582',
    projectId: 'login-task-98f8c',
    authDomain: 'login-task-98f8c.firebaseapp.com',
    storageBucket: 'login-task-98f8c.appspot.com',
    measurementId: 'G-F3PGNJ1SJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq6ym0KehSj9iapMrGMvC8wH-PUZA1bSw',
    appId: '1:271186785582:android:a61cdd794c829c476536bf',
    messagingSenderId: '271186785582',
    projectId: 'login-task-98f8c',
    storageBucket: 'login-task-98f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYaZw9vlcQxZ0XL0L5YQ93YhvM4QpUjyI',
    appId: '1:271186785582:ios:6dd9d450b126235f6536bf',
    messagingSenderId: '271186785582',
    projectId: 'login-task-98f8c',
    storageBucket: 'login-task-98f8c.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYaZw9vlcQxZ0XL0L5YQ93YhvM4QpUjyI',
    appId: '1:271186785582:ios:6dd9d450b126235f6536bf',
    messagingSenderId: '271186785582',
    projectId: 'login-task-98f8c',
    storageBucket: 'login-task-98f8c.appspot.com',
    iosBundleId: 'com.example.loginTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCgbJxEfn0AUJvJB1mHY_FM6mjQDaBMY',
    appId: '1:271186785582:web:7fff7407673ffa126536bf',
    messagingSenderId: '271186785582',
    projectId: 'login-task-98f8c',
    authDomain: 'login-task-98f8c.firebaseapp.com',
    storageBucket: 'login-task-98f8c.appspot.com',
    measurementId: 'G-MJ9H4TJPF4',
  );
}
